# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0002_summarize_urlid'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarize',
            name='summarized',
            field=models.CharField(default=1, max_length=3000),
            preserve_default=False,
        ),
    ]
