# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0003_summarize_summarized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarize',
            name='summarized',
            field=models.CharField(max_length=3000000),
        ),
    ]
